### ISSUE TITLE
Strain Sharing Metric

### ISSUE THREAD

**Issue by joshuakirsch** [human-nature-lab/strain_sharing#2]
Hi,

Thanks for sharing your code and the paper is a great work! I am wondering how to replicate your strain sharing metric from the paper. Here's the text from the paper:

> We summarized the strain-level similarity between two people with a strain-sharing rate metric that is equal to the number of shared strains divided by the number of species with available strain profiles that are present in any two samples.

My understanding is that a strain is an SGB and the presence of a strain in an individual is detection of an SGB. Can you please confirm if this is correct?

Thanks,
Josh

**Comment by fbeghini** [comment]
Hi Josh,
In this case, the SGB is the species, the SGB strain is inferred by looking at whether StrainPhlAn was able to reconstruct the strain from a sample.
Let me know if you have any more questions.

Best,
Francesco

From: joshuakirsch ***@***.***>
Date: Tuesday, December 3, 2024 at 12:48 PM
To: human-nature-lab/strain_sharing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [human-nature-lab/strain_sharing] Strain Sharing Metric (Issue #2)

Hi,

Thanks for sharing your code and the paper is a great work! I am wondering how to replicate your strain sharing metric from the paper. Here's the text from the paper:

We summarized the strain-level similarity between two people with a strain-sharing rate metric that is equal to the number of shared strains divided by the number of species with available strain profiles that are present in any two samples.

My understanding is that a strain is an SGB and the presence of a strain in an individual is detection of an SGB. Can you please confirm if this is correct?

Thanks,
Josh

**Comment by joshuakirsch** [comment]
Thanks for the reply! Would you mind walking me through how to generate this metric from two samples? I have been reading the strainphlan documentation but I am a little lost here.

Thanks,
Josh

**Comment by fbeghini** [comment]
Sure. The information about the presence of the same SGB between pairs of samples can be done by looking at the MetaPhlAn output table for SGB entries with relative abundance greater than zero. In order to establish if a sample has a SGB strain profiled by StrainPhlan, you can check if the sample is present in the pairwise distance matrix obtained from the phylogenetic tree (tree_pairwisedists.py).

The information on whether the strain between two samples is the same is retrieved from the output of strain_transmission.py. The final metric is obtained by dividing the sum of occurrences of same strains by the number of SGB shared by the two samples.

Best,
Francesco

From: joshuakirsch ***@***.***>
Date: Tuesday, December 3, 2024 at 1:03 PM
To: human-nature-lab/strain_sharing ***@***.***>
Cc: Beghini, Francesco ***@***.***>, Comment ***@***.***>
Subject: Re: [human-nature-lab/strain_sharing] Strain Sharing Metric (Issue #2)

Thanks for the reply! Would you mind walking me through how to generate this metric from two samples? I have been reading the strainphlan documentation but I am a little lost here.

Thanks,
Josh

**Comment by joshuakirsch** [comment]
Hi,

I think I figured out how to strain_transmission.py without reported error. However, the output files are not in agreement. In `transmission_events.info`, there are no reported transmission events. However, in the `.dist `file, there are distances that fall below the distance threshold and are in the same "network" as the sample. I've attached a tree, distance matrix, transmission_events.info, and the metadata file used. 
[stran_transmission_test.zip](https://github.com/user-attachments/files/17999360/stran_transmission_test.zip)

Also, for multiple SGBs, is the computed distance threshold a better cutoff than a standard distance threshold (eg 0.03)?

Thanks for all the help,
Josh

**Comment by fbeghini** [comment]
Hi Josh,
The metadata file looks good to me; it has been a while since I’ve looked at the strain_transmission script, but if I remember correctly, it reports a transmission event if the relationship is the same and the subject id is different, so in this case you should be encoding the subject id the same as the sample id in order to make it work

Best,
Francesco

From: joshuakirsch ***@***.***>
Date: Tuesday, December 3, 2024 at 4:37 PM
To: human-nature-lab/strain_sharing ***@***.***>
Cc: Beghini, Francesco ***@***.***>, Comment ***@***.***>
Subject: Re: [human-nature-lab/strain_sharing] Strain Sharing Metric (Issue #2)

Hi,

I think I figured out how to strain_transmission.py without reported error. However, the output files are not in agreement. In transmission_events.info, there are no reported transmission events. However, in the .dist file, there are distances that fall below the distance threshold and are in the same "network" as the sample. I've attached a tree, distance matrix, transmission_events.info, and the metadata file used.
stran_transmission_test.zip<https://github.com/user-attachments/files/17999360/stran_transmission_test.zip>

Also, for multiple SGBs, is the computed distance threshold a better cutoff than a standard distance threshold (eg 0.03)?

Thanks for all the help,
Josh

**Comment by joshuakirsch** [comment]
Ok I think that worked! Thanks for help and the quick replies!

Josh
